### ISSUE TITLE
Intergration not loading.

### ISSUE THREAD

**Issue by droeloe1818** [Athozs/hass-additional-ca#16]
**Describe the issue**

Intergration is not being loaded

**Describe your setup (please complete the following information):**

 - Installation type: Home Assistant OS in a VM in Proxmox
 - HAOS version (if applicable): 14.2
 - Home Assistant core version: 2025.1.4
 - Additional CA integration version: 0.2.4 
 - Kind of certificate you use: Used chrome to export is

**YAML configuration extract**

```yaml
# Loads default set of integrations. Do not remove.
default_config:

# Certificaat voor H0N, indien ooit verlopen nieuwe ophalen op https://account2.hon-smarthome.com en in additional_CA zetten             

additional_ca:                    
  RapidSSL: RapidSSL2.cer
  DigiCert: DigiCertGlobalRoot2.cer
# ...
```

**Logs**

There are no logs found in core, and supervisor when I search for additional_ca or additional etc.

the onlything I find is:

2025-02-07 15:33:04.608 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration additional_ca which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

**Additional context**

The intergration is showing when I try to add the intergration:

![Image](https://github.com/user-attachments/assets/d4ee68d8-d247-4a75-a518-7b428bec38a9)

When I add the code to my YAML configuration and I reboot the addon is now showing up on Discovered or Configured devices.

I created the folder:

![Image](https://github.com/user-attachments/assets/d12b17f7-1315-4f10-bd08-81f719794909)

I also tried with diffrent certificates with .crt extension but even then the intergration is not loading.

Nothing in the logs.
```
logger:
  default: info 
```
is enabled.

I realy need this to get working, all help is appriciated.
